const products = [
  {
    id: "gerald",
    name: "Gerald",
    shortDescription: "Gerald",
    description: "Gerald.<br><br>Printed on a soft Bella+Canvas 3001 tee.",
    price: 28,
    image: "Gerald.svg",
    stripeLink: "https://buy.stripe.com/YOUR_GERALD_LINK",
    placement: { size: 30, x: 35, y: 40 },
  },
  {
    id: "bernard",
    name: "Bernard",
    shortDescription: "A Hork, a Duorse, and Nigel.",
    description: "You can give a horse-water a fish, but you can't teach a fish to drink it.<br><br>Printed on a soft Bella+Canvas 3001 tee.",
    price: 28,
    image: "Bernard.svg",
    stripeLink: "https://buy.stripe.com/YOUR_BERNARD_LINK",
    placement: { size: 25, x: 38, y: 39 },
  },
  {
    id: "sid",
    name: "Sid",
    shortDescription: "Yummy",
    description: "His favorite color is perriwinkle.<br><br> Printed on a soft Bella+Canvas 3001 tee.",
    price: 28,
    image: "DuckCream.svg",
    stripeLink: "https://buy.stripe.com/YOUR_SID_LINK",
    placement: { size: 12, x: 45, y: 40 },
  },
  {
    id: "bartholomew",
    name: "Bartholomew",
    shortDescription: "Please be nice to him.",
    description: "Don't be mean to him. He's sensitive.<br><br> Printed on a soft Bella+Canvas 3001 tee.",
    price: 18,
    image: "Bartholomew.svg",
    stripeLink: "https://buy.stripe.com/YOUR_BARTHOLOMEW_LINK",
    placement: { size: 27, x: 37, y: 40 },
  },
  {
    id: "toby",
    name: "Toby",
    shortDescription: "WHYYYY!?!",
    description: "He has no mouth, and he must scream.<br><br>Printed on a soft Bella+Canvas 3001 tee.",
    price: 18,
    image: "Toby.svg",
    stripeLink: "https://buy.stripe.com/YOUR_LINK",
    placement: { size: 22, x: 40, y: 38 },
  },
];
