const products = [
  {
    id: "gerald",
    name: "Gerald",
    shortDescription: "Roller skates. Party hat. Zero explanation.",
    description: "Gerald showed up to someone else's birthday party on roller skates, ate their cake, and left on a skateboard. He is wearing a party hat. He holds what appears to be an ice cream cone. He does not explain himself. Printed on a soft Bella+Canvas 3001 tee.",
    price: 28,
    image: "Gerald.svg",
    stripeLink: "https://buy.stripe.com/YOUR_GERALD_LINK",
    placement: { size: 30, x: 35, y: 40 },
  },
  {
    id: "bernard",
    name: "Bernard",
    shortDescription: "A Hork, a Duorse, and Nigel.",
    description: "Bernard is a hork. On his back rides Nigel. On his hat sits Reggie, the Duorse. Bernard carries them all without complaint. They are good company for a Hork like Bernard. Printed on a soft Bella+Canvas 3001 tee.",
    price: 28,
    image: "Bernard.svg",
    stripeLink: "https://buy.stripe.com/YOUR_BERNARD_LINK",
    placement: { size: 25, x: 38, y: 39 },
  },
  {
    id: "sid",
    name: "Sid",
    shortDescription: "Cold snack, says quack.",
    description: "Sid is a duck whose entire body is a soft-serve ice cream cone. He has a violent red punk mohawk. He does not have legs. He does not need legs. Named after Sid Vicious, who also did not need legs. Printed on a soft Bella+Canvas 3001 tee.",
    price: 28,
    image: "DuckCream.svg",
    stripeLink: "https://buy.stripe.com/YOUR_SID_LINK",
    placement: { size: 12, x: 45, y: 40 },
  },
  {
    id: "bartholomew",
    name: "Bartholomew",
    shortDescription: "Herein flies Bartholomew. Thou art warned.",
    description: "Hark. What manner of creature dost traverse yon sky with such confidence? Tis Bartholomew the Clappinator, hoarder of muffins. Ye be warned. Printed on a soft Bella+Canvas 3001 tee.",
    price: 28,
    image: "Bartholomew.svg",
    stripeLink: "https://buy.stripe.com/YOUR_BARTHOLOMEW_LINK",
    placement: { size: 27, x: 37, y: 40 },
  },
];
